### ISSUE TITLE
To Do in Documentation

### ISSUE THREAD

**Issue by MitraDarja** [seqan/seqan3#1027]
- [x] A short sentence to describe what Configuration does on the Alignment overview in API references (modules)
- [x] Write detailed landing page for alignment
- [x] Write detailed landing page. for band in alignment (seqan/seqan3#1956)
- [x] banded section in Alignment configuration
- [x] Write detailed landing page. for matrix in alignment. (https://github.com/seqan/seqan3/issues/1957)
- [x] Document EditDistanceTrait in Alignment.
- [x] Function table in Alignment Matrix overview is too wide.
- [x] Table in Alphabet Overview for Different concepts is too wide. (Plus, there are some weird boxes in column Aux)
- [x] Link to customisation point manual in alphabet_size, in assign_char_to, assign_rank_to, char_is_valid_for, to_char, to_rank
- [x] weird spacing in is_char_adaptation_v, is_uint_adaptation_v
- [x] fix table private attributes in argument parser, is too wide
- [x] Related functions in validator of argument parser looks incomplete
- [x] Detailed description in validator_concept looks incomplete (https://github.com/seqan/seqan3/issues/1961)
- [x] Table Variables in core algorithm too wide
- [x] Write detailed landing page concept in core (https://github.com/seqan/seqan3/issues/1958)
- [x] Table Type definition in simd too wide
- [x] Write detailed description in simd (https://github.com/seqan/seqan3/issues/1959)
      Will be done once SIMD becomes non detail code
- [x] Write detailed description alignment file in IO
- [x] read_groups in alignment file in IO, barcode table is not correctly shown , same problem in ref_id_info
- [x] Type deduction guides table in alignment file in  IO too wide
- [x] give overview of formats, once they are all implemented in alignment file input in IO
- [x] TODO linear in the size of the written alignments? in emplace_back()(push_back in IO 
- [x] Write detailed description for sequence files in IO
- [x] Missing link to quality submodule in format_fastaq
- [x] table which files take which fields in seqan3::fields
- [x] Rewrite landing page. for kmer-indices in FM-Index (https://github.com/seqan/seqan3/issues/1960)
- [x] Update concepts and documentation of configuration_t everywhere once it has been refactored by rrahn.
- [x] (between a factor of X and Y depending on the configuration). in FM Indicies

Death links:
- [x] ~std::Equality_comparable in mask in Alphabet~
- [x] ~std::contrib::latch in Core Parallel`~
- [x] ~cereal::BinaryInputArchive, cereal::PortableBinaryInputArchive, cereal::JSONInputArchive, and cereal::XMLInputArchive~ documented in a cereal tutorial
- [x] concat_capacity() to concat_size() in Container
- [x] ~seqan3::detail::transformation_trait_or_t~

Limitations of doxygen 
- `seqan3::alphabet_size` is never linked correctly in snippets (templated functions are not recognized correctly)
- `seqan3::d/rna*_vector` in `operator""_d/rna*()` in Nucleotide  (`operator""_` is not recognized correctly)

**Comment by marehr** [comment]
```
This is a code snippet. You will see many code snippets in our documentation. Most of them are compilable as-is, but some are only valid in their context, e.g. they depend on other code snippets given before/after the current one or other statements implied by the text. You can copy'n'paste freely from these examples, this implies no copyright-obligations (however distributing SeqAn3 or an application using it does, see "Copyright and Citing").
```
Make a link to Copyright and Citing.

**Comment by h-2** [comment]
http://docs.seqan.de/seqan/3-master-user/todo.html

**Comment by h-2** [comment]
What is the state here? Lot's of it got fixed for the release, did someone keep track?

**Comment by smehringer** [comment]
I checked off the ones I did :white_check_mark:

**Comment by smehringer** [comment]
@jwinkler Since Mitra is not working on Seqan currently, could check the documentation? :)

**Comment by eseiler** [comment]
@MitraDarja Can you check which points are still relevant?
Quick scan would suggest `concat_capacity() to concat_size() in Container` but the rest seems rather resolved?

**Comment by smehringer** [comment]
This is done with #3064
