### ISSUE TITLE
Rename back/front coordinate AND update docu

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1112]
### Rename
* back_coordinate -> ???
* front_coordinate -> ???

### Documentation issues:
pointed out by @joergi-w in https://github.com/seqan/seqan3/pull/1093#pullrequestreview-252185043

 * https://github.com/seqan/seqan3/blob/21541d64a4259e97976e71008f63903da7145514/include/seqan3/alignment/all.hpp#L110-L114
   
   > The back coordinate stores the end of the alignment within both sequences. Note that theses positions are **inclusive**.
   
   http://docs.seqan.de/seqan/3-master-dev/group__alignment.html#autotoc_md3
  
 * https://github.com/seqan/seqan3/blob/af37e5ba74f18d637cc4f5821ac62b4fa7d54cda/include/seqan3/alignment/configuration/align_config_result.hpp#L28-L32
   
   > Triggers score computation and determines the end position of the sequence alignment. 
   
   http://docs.seqan.de/seqan/3-master-dev/structseqan3_1_1detail_1_1with__back__coordinate__type.html
   > @joergi-w: could also need some information that the coordinate is exclusive.

There could be more documentation issues. 

### Task (from the resolution below)

- [ ] Add four member functions: sequence1_begin_position(), sequence2_begin_position(), sequence1_end_position(), sequence2_end_position()
- [ ] The respective member functions are only available if the associated configuration was set in the alignment configuration object: (sequenceX_end_position() -> with_end_position), (sequenceX_begin_position() -> with_begin_position)
- [ ] The return type is auto and the method throws a static assert if it was not configured properly.
- [ ] Test that the end position is exclusive. Such that the position behind the last valid one.
- [ ] Fix all tests that assume an inclusive back_coordinate
- [ ] Check that edit distance and standard alignment behave the same (different algorithms)

Example code:
```cpp
for (auto && alignment : align_pairwise(sequence_pairs, config)
{
    auto sequence1_slice = sequence_pairs[alignment.id()].first 
                         | views::slice(alignment.sequence1_begin_position(), alignment.sequence1_end_position());
    auto sequence2_slice = sequence_pairs[alignment.id()].second 
                         | views::slice(alignment.sequence2_begin_position(), alignment.sequence2_end_position());
    // do something with the slices...
}
```

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] API documentation updated
- [ ] Tutorial/teaching material updated
- [ ] Changelog entry added

**Comment by smehringer** [comment]
@marehr whats the state of this?

**Comment by rrahn** [comment]
We should remove the interface completely. It doesn’t help the user to get a matrix position back since he doesn’t care about the internal structure of the algorithm. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by joergi-w** [comment]
Wait... As a user I want to know the start and end position of a local or semi-global alignment. I agree that the term _coordinate_ is too technical, but we should still provide the location of an alignment.

**Comment by rrahn** [comment]
> Wait... As a user I want to know the start and end position of a local or semi-global alignment. I agree that the term coordinate is too technical, but we should still provide the location of an alignment.

Sorry, that was to unspecific. Of course we continue to output the positions but not as pairs/coordinates but as single positions.

**Comment by smehringer** [comment]
Resolution: 
We want one slice struct with four members (aligned_region.first_begin_position, ...)
