### ISSUE TITLE
Alignment Vectorisation - add score_type to result configuration

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1299]
```c++
seqan3::align_cfg::result{seqan3::with_score} // current: defaults to int32_t
seqan3::align_cfg::result<int16_t>{seqan3::with_score} // new syntax
```

**TASK: Add score_type to align_cfg::result**

- [x] Change definition of [align_cfg::result](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/configuration/align_config_result.hpp#L90-L97)
- [x] Add default value to type deduction guides.
- [x] ~~Add tests to [align_config_common_test.cpp](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/test/unit/alignment/configuration/align_config_common_test.cpp)~~ not applicable any more because the default result config did not change
- [x] Add tests to [align_config_result_test.cpp](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/test/unit/alignment/configuration/align_config_result_test.cpp)
- [x] Update snippet
- [x] Update Documentation
