### ISSUE TITLE
Are matrices simd aware? - check if value type `simd_type` is working in two_dimensional_matrix

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1300]
**TASK: check if value type `simd_type` is working in two_dimensional_matrix**

- [x] check if `seqan3::detail::two_dimensional_matrix<simd_type<int>>` is working; see [two_dimensional_matrix](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp#L58-L61) and [simd_type](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/core/simd/simd.hpp#L45-L48)
- [x] add tests to [two_dimensional_matrix_test.cpp](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp#L26-L33)
- [x] create some constants `auto one = seqan3::simd::fill<simd_t>(1)`, `auto iota = seqan3::simd::iota<simd_t>()` and fill the matrix with those constants
- [x] compile this test locally with `-msse4` and `-O3` to see if it is working
- [x] (NOTE: Our build system does not support compiling and testing it for different CPU instruction sets, yet)
