### ISSUE TITLE
Range awareness - level1

### ISSUE THREAD

**Issue by svnbgnk** [seqan/seqan3#1308]
**TASK: execution_handler_sequential should operate on a range of sequence pairs**

- [x] add interface that takes range of sequence pairs, i.e. `execution_handler.execute(config, start_id, [(s1,s2),...],callback)` in execution_handler_sequential; see [execution_handler_sequential](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/pairwise/execution/execution_handler_sequential.hpp#L53-L58)
- [x] in execute: call algorithm on each sequence pair in range and execute callback on the results.
- [x] add documentation; no new tests

**Comment by rrahn** [comment]
resolved by #1325
