### ISSUE TITLE
New configurations – vectorise and parallel

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#1309]
```c++
seqan3::align_cfg::vectorise{}

seqan3::align_cfg::parallel{} // default to max threads
seqan3::align_cfg::parallel{5} // uses 5 threads
```

**TASK: add config id's**

- [x] add config id `parallel` and  `vectorise` to [alignment/configuration/detail.hp](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/configuration/detail.hpp#L23-L35)
- [x] and change [support matrix](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/configuration/detail.hpp#L47-L61) (vectorise should be combinable with all, except itself)
- [x] make tests work again; no new tests
