### ISSUE TITLE
### Vectorise Scoring Schemes - level1

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1319]
```c++
using score_type = int;
using simd_t = simd_type<score_type>;

nucleotide_scoring_scheme nucl_scheme{};

vectorised_scoring_scheme<simd_t> vec_scheme{nucl_scheme};

simd_t a = seqan3::simd::fill<simd_t>(1); // [C,C,C,C,C,C,...]
simd_t b = seqan3::simd::fill<simd_t>(2);
b[0] = 1; // [C,G,G,G,G,G,...]
vec_scheme.score(a, b); // [0, -1, -1, -1, ...]
```

**TASK: write class that converts a scoring_scheme into a vectorised scoring_scheme I/II**

- [x] TODO: where to place this class
- [x] Add `vectorised_scoring_scheme` in [include/seqan3/alignment/scoring](https://github.com/seqan/seqan3/tree/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/scoring)
- [x] Write tests, s.t. vectorised_scoring_scheme will be tested on any given scoring scheme
- [x] (NOTE: You don't have to vectorise anything, or better stated you don't have to do anything clever, you can loop in the score function and produce the result)
