### ISSUE TITLE
Vectorise configuration

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#1321]
**TASK: Add vectorise configuration**

- [x] Depends on [add config id's](https://github.com/seqan/seqan3/projects/10#card-27980956)
- [x] Create a new file `align_config_vectorise.hpp` in [include/seqan3/alignment/configuration](https://github.com/seqan/seqan3/tree/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/configuration)
- [x] Use [align_config_max_error](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/configuration/align_config_max_error.hpp#L36-L41) as a starting point
- [x] Add `align_cfg::vectorise` to [align_config_common_test.cpp](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/test/unit/alignment/configuration/align_config_common_test.cpp)
- [x] Add a new test in [test/unit/alignment/configuration](https://github.com/seqan/seqan3/tree/8993bb63efa8f844f23bd2207e9bac1061c94bd1/test/unit/alignment/configuration)
- [x] Add snippet and doc.
- [x] Adapt documentation in `enum align_config_id`
