### ISSUE TITLE
Range awareness - level1

### ISSUE THREAD

**Issue by svnbgnk** [seqan/seqan3#1328]
**TASK: add new call operator to alignment_algorithm**

- [x] Add new call operator; see [alignment_algorithm.hpp](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/pairwise/alignment_algorithm.hpp#L143-L146)
- [x] that takes a range, calls the two sequences call operator on each sequence pair and writes the results into a vector, return the vector
- [x] no tests needed, add new documentation
