### ISSUE TITLE
Apply vectorise and parallel configs

### ISSUE THREAD

**Issue by joergi-w** [seqan/seqan3#1336]
**TASK: Use configuration (keep old infrastructure for now)**

- [x] Depends on [Add parallel configuration](https://github.com/seqan/seqan3/projects/10#card-27981006)
- [x] Depends on [Add vectorise configuration](https://github.com/seqan/seqan3/projects/10#card-27981306)
- [x] In [align_parwise](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/pairwise/align_pairwise.hpp#L171-L180) convert `vectorise` and `parallel` config to `seqan3::unseq` or `seqan3::par` or `seqan3::par_seq`
- [x] Write `alignment_algorithm` tests that use the `parallel` config
