### ISSUE TITLE
### Range awareness - level2

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1353]
**TASK: add new parameter to alignment_executor_two_way constructor for chunking**

- [ ] Depends on [only one constructor for alignment_executor_two_way](https://github.com/seqan/seqan3/projects/10#card-27977457)
- [ ] add new chunking parameter `alignment_executor_two_way{sequence_pair_range,algorithm, execution_policy[, chunking = 1]}`
- [ ] test new parameter interface
- [ ] add documentation
- [ ] (NOTE: This does not require actual chunking, only adapt the (public) API)
