### ISSUE TITLE
### Range awareness - level3

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1355]
**TASK: Chunk range of sequence pair according to the given parameter in alignment_executor_two_way**

- [ ] Depends on [add new parameter to alignment_executor_two_way constructor for chunking](https://github.com/seqan/seqan3/projects/10#card-27977538) (#1354)
- [ ] Chunk the range accordingly.
- [ ] [OPTION1] Call execution handler on each element in the chunk. See [alignment_executor_two_way](https://github.com/seqan/seqan3/blob/8993bb63efa8f844f23bd2207e9bac1061c94bd1/include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp#L220-L231)
- [ ] [OPTION2] This task can be merged with the task [Chunk range of sequence pair according to the given parameter in alignment_executor_two_way](https://github.com/seqan/seqan3/projects/10#card-27979762) if the dependencies in that task are met
