### ISSUE TITLE
### Range awareness - level2

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1357]
**TASK: Pass given range directly in execution handler**

- [ ] Depends on [execution_handler_sequential should operate on a range of sequence pairs](https://github.com/seqan/seqan3/projects/10#card-27977085)
- [ ] Depends on [execution_handler_parallel should operate on a range of sequence pairs](https://github.com/seqan/seqan3/projects/10#card-27977114)
- [ ] Depends on [add new call operator to alignment_algorithm](https://github.com/seqan/seqan3/projects/10#card-27976414)
- [x] Depends on 
[add new call operator to edit_algorithm](https://github.com/seqan/seqan3/projects/10#card-27976547)
- [x] Instead of calling algorithm on each sequence pair, pass range directly to the alignment algorithm
