### ISSUE TITLE
### Range awareness - level4

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1372]
**TASK: Pass a chunk of the range directly to the execution handler**

- [x] Depends on [Chunk range of sequence pair according to the given parameter in alignment_executor_two_way](https://github.com/seqan/seqan3/projects/10#card-27977713)
- [x] Depends on [execution_handler_sequential should operate on a range of sequence pairs](https://github.com/seqan/seqan3/projects/10#card-27977085)
- [x] Depends on [execution_handler_parallel should operate on a range of sequence pairs](https://github.com/seqan/seqan3/projects/10#card-27977114)
- [x] Pass range of sequence pairs (chunk) directly to the execution_handler
- [x] Use the new `exec_handler.execute(kernel, start_id, chunk, callback)` syntax.
