### ISSUE TITLE
### Range awareness - level5

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#1375]
**TASK: Remove (single) sequence pair syntax in execution_handler_sequential and execution_handler_parallel**

- [x] Depends on [Pass a chunk of the range directly to the execution handler](https://github.com/seqan/seqan3/projects/10#card-27979762)
- [x] Remove (single) sequence pair syntax in execution_handler_sequential and execution_handler_parallel
- [x] update documentation and tests
