### ISSUE TITLE
gcc-10 -std=c++17 support

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1502]
Keeps track of all changes for gcc10

Bugfixes:
* [x] [MISC] prepare span header for gcc10 (#1478)
* [x] [MISC] scoring scheme: concept template paramater can't be constrained (#1539)
* [x] [FIX] trace_iterator_base: use same constraints (#1538)
* [x] [FIX] alignment matrix tests (#1537)
* [x] [MISC] remove restraints on comparison operators of small string (#1536)
* [x] [FIX] enums shouldn't be used with same_as (#1535)
* [x] [FIX] add ; after requires expression (#1534)
* [x] [MISC] gap_scheme and static_band needs stdexcept (#1533)
* [x] [FIX] forward declare must use the same declaration (#1532)
* [x] [TEST] Don't static_assert concepts (#1531)
* [x] [TEST] two_dimensional_matrix_test use original fix again (#1530)
* [x] [FIX] break up cyclic include of std/range and std/iterator (#1529 )

Error Classes:

* [x] BUG_ALIGNED_SEQUENCE_TEST_TEMPLATE
* [x] BUG_ALPHABET_ANY
* [x] BUG_ALPHABET_TUPLE_BASE
* [x] BUG_CONCATENATED_SEQUENCES
* [x] BUG_CONCATENATED_SEQUENCES_BITCOMPRESSED_CONTAINER
* [x] BUG_RANGE_EMPLACE
* [x] BUG_RANGE_META_IS_BASE_OF
* [x] BUG_TUPLE_LIKE seems to be also caused by BUG_ALPHABET_TUPLE_BASE

<details><summary>See overview of affected test cases</summary>

**BUG_ALIGNED_SEQUENCE_TEST_TEMPLATE**:
  * seqan3_test(aligned_sequence_test.cpp)

**BUG_ALPHABET_ANY**:
  * seqan3_test(semialphabet_any_test.cpp)

**BUG_ALPHABET_TUPLE_BASE**:
  * seqan3_test(alphabet_tuple_base_test.cpp)
  * seqan3_test(composite_integration_test.cpp)
  * seqan3_test(qualified_test.cpp)
  * seqan3_test(structured_aa_test.cpp)
  * seqan3_test(structured_rna_test.cpp)
  * seqan3_test(debug_stream_alphabet_test.cpp)

**BUG_CONCATENATED_SEQUENCES**:
  * seqan3_test(debug_stream_container_of_container_test.cpp)

**BUG_CONCATENATED_SEQUENCES_BITCOMPRESSED_CONTAINER**:
  * seqan3_test(container_of_container_test.cpp)

**BUG_RANGE_EMPLACE**:
  * seqan3_test(aminoacid_translation_test.cpp)
  * seqan3_test(format_parse_validators_test.cpp)
  * seqan3_test(view_interleave_test.cpp)
  * seqan3_test (search_collection_test.cpp)
  * seqan3_test(fm_index_dna4_test.cpp)
  * seqan3_test(bi_fm_index_dna4_test.cpp)
  * seqan3_test(bi_fm_index_aa27_test.cpp)
  * seqan3_test(bi_fm_index_char_test.cpp)
  * seqan3_test(fm_index_cursor_collection_test.cpp)
  * seqan3_test(bi_fm_index_cursor_collection_test.cpp)

**BUG_RANGE_META_IS_BASE_OF**:
  * seqan3_test(align_pairwise_test.cpp)
  * seqan3_test(global_affine_banded_test.cpp)
  * seqan3_test(global_affine_unbanded_collection_test.cpp)
  * seqan3_test(global_affine_unbanded_test.cpp)
  * seqan3_test(local_affine_banded_test.cpp)
  * seqan3_test(local_affine_unbanded_test.cpp)
  * seqan3_test(semi_global_affine_banded_test.cpp)
  * seqan3_test(semi_global_affine_unbanded_test.cpp)

  * seqan3_test(format_help_test.cpp)
  * seqan3_test(format_bam_test.cpp)
  * seqan3_test(format_sam_test.cpp)
 
  * seqan3_test(alignment_file_output_test.cpp)
  * seqan3_test(alignment_file_input_test.cpp)

  * seqan3_test(sequence_file_input_test.cpp)
  * seqan3_test(sequence_file_integration_test.cpp)
  * seqan3_test(sequence_file_output_test.cpp)
  * seqan3_test(sequence_file_format_embl_test.cpp)
  * seqan3_test(sequence_file_format_fasta_test.cpp)
  * seqan3_test(sequence_file_format_fastq_test.cpp)
  * seqan3_test(sequence_file_format_genbank_test.cpp)
  * seqan3_test(sequence_file_format_sam_test.cpp)
 
  * seqan3_test(format_vienna_test.cpp)
  * seqan3_test(structure_file_input_test.cpp)
  * seqan3_test(structure_file_output_test.cpp)

**BUG_TUPLE_LIKE**:
  * seqan3_test(view_get_test.cpp)

</details>

External Libraries (Upstream) reported:
* [x] BUG_RANGE_EMPLACE: ambigious overload for ranges::emplace on chunk_view + join and gcc10 (https://github.com/ericniebler/range-v3/issues/1414)
* [x] BUG_RANGE_META_IS_BASE_OF: gcc10 invalid use of incomplete type ‘struct std::tuple_size<std::thread>’ (https://github.com/ericniebler/range-v3/issues/1430)

Reported ICEs:
* [x] [10 Regression] ICE with -Wall on constexpr if (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93324)
* [x] [10 Regression] internal compiler error: in build_value_init_noctor, at cp/init.c:400 using std::tuple (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92594)
* [x] [10 Regression] internal compiler error: in lazily_declare_fn, at cp/method.c:3045 with -fconcepts (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92552)
* [x] [10 Regression] internal compiler error: Segmentation fault with concept on constructor (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92582)
* [x] [10 Regression] ICE: in tsubst, at cp/pt.c:15142 on friends with concepts (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93400)
* [ ] [7,8,9,10] ICE: Segmentation fault on invalid concept code gcc/gcc/cp/constraint.cc:2537 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93664)
* [x] [10 regression] ICE in esra with nested [[no_unique_address]] field (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93667) (BUG_RANGE_EMPLACE)
* [x] [10 Regression] ice in propagate_vals_across_arith_jfunc, at ipa-cp.c:2039 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93799)
* [x] [10 Regression] Inherited and constrained constructors are "ambiguous" even if they aren't (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94549) (BUG_ALPHABET_TUPLE_BASE)
* [x] [10 Regression] Inherited and constrained constructors are "ambiguous" even if they aren't Pt. 2 (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94819) (BUG_ALPHABET_TUPLE_BASE)
