### ISSUE TITLE
3.0.1 Release

### ISSUE THREAD

**Issue by smehringer** [seqan/seqan3#1509]
- [x] Check [Nightlies](http://cdash.seqan.de/index.php?project=SeqAn3) for critical build failures.
- [x] Check Changelog.md for completeness (#1493).
- [x] Update the index from cppreferences.com so that up-to-date documentation links are generated (#1511).
- [x] Prepare `seqan-[VERSION]-with-submodules.tar.gz`.
- [x] Add 3.0.0 documentation build on docs.seqan.de (has been missing so far).
- [x] Add 3.0.1 documentation build on docs.seqan.de.

- [x] **Tag release on Github and attach `seqan-[VERSION]-with-submodules.tar.gz` to the release.**

- [x] Bump succeeding version number. ([include/seqan3/version.hpp](https://github.com/seqan/seqan3/blob/6391aaa014db4d04b8220a2041014295c4134f33/include/seqan3/version.hpp#L19-L24)) (#1517)
- [x] update seqan and app versions in the resource.txt file on the server in Tuebingen
- [x] Announce release on twitter.
- [x] Announce release on www.seqan.de.
- [x] Announce release on mailing list `seqan-dev@lists.fu-berlin.de`.
- [x] Announce release on public Gitter channel [![Gitter](https://badges.gitter.im/seqan/Lobby.svg)](https://gitter.im/seqan/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).
- [x] Celebrate :tada: :beer:

**Comment by h-2** [comment]
See also https://github.com/seqan/seqan/wiki/Release-Checklist

**Comment by smehringer** [comment]
:D The only thing left to do is to refurbish the release check list a little
