### ISSUE TITLE
cxx20: view_to_simd is not an input_range

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#1941]
@marehr commented on [Mon Jun 08 2020](https://github.com/seqan/product_backlog/issues/120)

### Description 

To model input_iterator, the reference and value type need to have a common type.

```c++
    using reference = std::span<std::ranges::range_value_t<chunk_type>>; //!< The reference type.
    using value_type = chunk_type; //!< The value type.
```
https://github.com/seqan/seqan3/blob/cf2505cb51715f89f1bc0c658f681f36fac89dfa/include/seqan3/core/simd/view_to_simd.hpp#L210-L211

The problem is that `std::span<simd_t>` and `chunk_type = std::array<simd_t, simd_traits<simd_t>::length>` don't have a common type.

### Tasks

 

- [ ] task 1
- [ ] task 2
- [ ] task 3

### Definition of Done

- [ ] Implementation and design approved
- [ ] Unit tests pass
- [ ] Test coverage = 100%
- [ ] Microbenchmarks added and/or affected microbenchmarks < 5% performance drop
- [ ] API documentation added
- [ ] Tutorial/teaching material added
- [ ] Test suite compiles in less than 30 seconds (on travis)
- [ ] Changelog entry added

---

@h-2 commented on [Tue Jun 09 2020](https://github.com/seqan/product_backlog/issues/120#issuecomment-641250726)

There already is a workaround for this here:
https://github.com/seqan/seqan3/blob/master/include/seqan3/range/container/concatenated_sequences.hpp#L35

**Comment by rrahn** [comment]
fixed by seqan/seqan3/#1942
