### ISSUE TITLE
3.0.2 Release

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#2001]
- [x] Create a release branch, e.g. `release-3.0.3`
- [x] Check for critical performance regressions. Use https://github.com/wvandertoorn/cmp_benchmarks
- [x] Check [Nightlies](http://cdash.seqan.de/index.php?project=SeqAn3) for critical build failures. Change nightlies to build on release branch.
- [x] Check workarounds in `platform.hpp`. Are they still valid or can they be limited to specific compiler versions.
- [x] Check the [Changelog.md](https://github.com/seqan/seqan3/blob/master/CHANGELOG.md) for completeness (including changed headers).
- [x] Update the index from cppreference.com so that up-to-date documentation links are generated.
  <details><summary>Click for detailed steps</summary><br>

  Check for [new releases](https://github.com/PeterFeicht/cppreference-doc/releases) and update the link and hash
  in the [code base](https://github.com/seqan/seqan3/blob/b0b279689fa65c2431a5162f2d8acc3ca663f72d/test/documentation/seqan3-doxygen.cmake#L37).

  For the hash do

  ```
  wget -O- <link to html book> | sha256sum
  ```

  </details>
- [x] Add versioned documentation build on docs.seqan.de.
  <details><summary>Click for detailed steps</summary>

  1. Build the documentation locally

  2. Create a #.#.# directory for the release in `/web/docs.seqan.de/htdocs/seqan/`

  3. Copy everything from the local build (`doc_usr/html/*`) into the directory.

  4. Alter the file `/web/docs.seqan.de/htdocs/seqan3.html` with a link to the new documentation build.

  </details>
- [x] Prepare `seqan3-[VERSION]-{Linux,Source}.tar.xz{,.sha265}`.
  <details><summary>Click for detailed steps</summary><br>

  Make a fresh clone of the repository and recursively delete the `.git` directories.
  ```
  mkdir package-build

  git clone https://github.com/seqan/seqan3.git
  cd seqan3

  git checkout 3.0.2 # version to pack

  git submodule init
  git submodule update

  cd ../package-build

  cmake ../seqan3 # configure

  cpack # builds binary package, e.g. seqan3-3.0.2-Linux.tar.xz{,.sha265}

  cmake --build . --target package_source # builds source package, e.g. seqan3-3.0.2-Source.tar.xz{,.sha265}
  ```

  Note: Do not do `git clone -recurse-submodules https://github.com/seqan/seqan3.git` because it will recursively
  pull sub-submodules which we do not want!

  </details>
- [x] Prepare a release note with notable features, API changes, bugs, and external dependency updates.

---

- [x] **Tag release on Github and attach `seqan3-[VERSION]-{Linux,Source}.tar.xz{,.sha265}` to the release.**

  <details><summary>Click for detailed steps</summary><br>

  Github is not able to create annotated releases (https://github.com/seqan/product_backlog/issues/159), so we have to manually sign the release.
  ```bash
  git checkout release-3.x.y
  git tag -s 3.x.y
  git push upstream 3.x.y
  ```

  You will need to provide a tag message. We use the first sentences of the release note:
  
  E.g. (see https://github.com/seqan/seqan3/tags)
  ```
  SeqAn 3.0.2 Release


  Despite all circumstances, we are excited to present a new update of our SeqAn library.
  We present some great new features and also a lot of usability improvements.
  Among others, this release will fully comply with the final C++-20 standard.

  :warning: In this release we harmonised the algorithm configurations for a better user experience.
  This, much like 2020, will break a lot of code. But rest assured that the changes are easy to apply and are worth every bit. :smile:

  You can find a comprehensive list of the changes in our [changelog](http://docs.seqan.de/seqan/3.0.2/about_changelog.html).
  ```

  </details>

---

- [x] Merge release branch into master.
- [x] Bump succeeding version number in master. ([include/seqan3/version.hpp](https://github.com/seqan/seqan3/blob/6391aaa014db4d04b8220a2041014295c4134f33/include/seqan3/version.hpp#L19-L24))
- [x] Update the SeqAn version [here](https://github.com/OpenMS/usage_plots/blob/master/seqan_versions.txt) to ensure
      that the server in Tübingen, which takes care of the argument parser update notifications, is aware of it
      (@smehringer).
- [x] Delete release branch.
- [x] Announce release on twitter (https://twitter.com/seqanlib).
- [x] Announce release on www.seqan.de.
- [x] Announce release on mailing list `seqan-dev@lists.fu-berlin.de`.
- [x] Announce release on public Gitter channel [![Gitter](https://badges.gitter.im/seqan/Lobby.svg)](https://gitter.im/seqan/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge).
- [x] Notify upstream package maintainers
  - [x] brew (@rrahn) PR: https://github.com/brewsci/homebrew-bio/pull/1165
  - [x] macports (@rrahn) PR: https://github.com/macports/macports-ports/pull/8769
  - [x] conda (@eseiler)
  - [x] debian (@mr-c)
  - [x] fedora (@sagitter)
- [x]  add seqan3 to https://github.com/rigtorp/awesome-modern-cpp.
- [x]  update release template with the current release tasks 🍻 .
- [x] Celebrate :tada: :beer:

**Comment by mr-c** [comment]
I would like to test a pre-release for Debian. Should I take a snapshot now, or should I wait a little longer?

**Comment by mr-c** [comment]
gcc 10.2 compatibility should be added to the Changelong

**Comment by marehr** [comment]
> I would like to test a pre-release for Debian. Should I take a snapshot now, or should I wait a little longer?

I think you can do a snapshot, because of the vacation time and the current low output, there shouldn't be anything game-changing until the release.

I thought about adding a step for a (temporary) feature freeze branch, maybe called `release-3.0.x`, to avoid conflicting last minute changes / to allow a smooth transition between the current and the next release.

But we actually need to discuss what (final) changes we want in release 3.0.2, I guess gcc-10.2 was one of them :)

**Comment by marehr** [comment]
Hi @seqan/team,
/cc: @mr-c, @sagitter

we are in our final sprint before the next release. :confetti_ball:

We created a new branch `release-3.0.2`, which will act as release-candidate branch. Every PR which fixes one of our open tasks should be created against this `release-3.0.2` branch. Everything unrelated to the release should use the master branch.

This means if you work on any of those task you should first checkout the `release-3.0.2` branch, create a new branch and then do your changes.

The workflow would be like this:

```bash
# within the seqan3 repository
git fetch upstream
git checkout upstream/release-3.0.2 # switch to the current release branch
git checkout -b <my_new_branch_name>

# ... work on my stuff, commit and push
git commit
git push origin <my_new_branch_name>
```

When creating a new PR make sure to select `release-3.0.2` as base.  (Try to avoid pulling the current master into that branch).

A short Rational:
- This will ensure that we only pull in changes that are needed for the release.
- We don't have any last-minute (unrelated) changes within our next release / merge-conflicts will be lesser.
- We have a release candidate branch that our volunteering package maintainer can use (to test their set-up)
- You can work on new things / create patches during our release (by creating PR against master).
- We'll regularly pull in the changes from the `release-3.0.2` into the master.

**Comment by marehr** [comment]
- [ ] Check if all moved headers are listed in the CHANGELOG 

My use case: 

```patch
-#include <seqan3/alignment/configuration/align_config_scoring.hpp>
+#include <seqan3/alignment/configuration/align_config_scoring_scheme.hpp>
```

**Comment by joergi-w** [comment]
The list of changed filenames since 3.0.1 release:
```console
[*.hpp]
include/seqan3/alignment/configuration/{align_config_max_error.hpp => align_config_min_score.hpp}
include/seqan3/alignment/configuration/{align_config_scoring.hpp => align_config_scoring_scheme.hpp}
include/seqan3/alignment/configuration/{align_config_vectorise.hpp => align_config_vectorised.hpp}
include/seqan3/{core => argument_parser}/detail/terminal.hpp
include/seqan3/{alignment/band => core/algorithm/detail}/all.hpp
include/seqan3/range/views/{trim.hpp => trim_quality.hpp}
include/seqan3/search/{algorithm => }/detail/search_common.hpp
include/seqan3/search/{algorithm => }/detail/search_scheme_algorithm.hpp
include/seqan3/search/{algorithm => }/detail/search_scheme_precomputed.hpp
include/seqan3/search/{kmer_index => dream_index}/all.hpp
test/unit/{alignment/pairwise/execution => core/algorithm/detail}/execution_handler_template.hpp
test/unit/range/container/{container_test.cpp => container_test_template.hpp}

[*.cpp]
test/snippet/core/algorithm/{configuration_value_or.cpp => configuration_get_or.cpp}
test/unit/alignment/configuration/{align_config_vectorise_test.cpp => align_config_vectorised_test.cpp}
test/unit/alignment/pairwise/{global_affine_unbanded_collection_test.cpp => global_affine_unbanded_collection_callback_test.cpp}
test/unit/{alignment/pairwise/alignment_range_test.cpp => core/algorithm/algorithm_result_generator_range_test.cpp}
test/unit/{alignment/pairwise/execution => core/algorithm/detail}/execution_handler_parallel_test.cpp
test/unit/{alignment/pairwise/execution => core/algorithm/detail}/execution_handler_sequential_test.cpp
test/unit/{alignment/band/static_band_test.cpp => core/detail/debug_stream_type_tuple_alignment_test.cpp}
test/unit/{alignment/band/static_band_test.cpp => core/detail/strong_type_debug_stream_test.cpp}
test/unit/{core/simd/detail/default_simd_backend_test.cpp => range/views/view_zip_test.cpp}
include/seqan3/range/detail/enable_view.hpp => test/unit/std/algorithm_test.cpp
test/unit/std/{charconv_test.cpp => charconv_float_test.cpp}

[other]
test/unit/{alignment/pairwise/execution => core/algorithm/detail}/CMakeLists.txt
```

**Comment by mr-c** [comment]
70dff0c builds fine in Debian !

**Comment by rrahn** [comment]
### Changelog TODOS:

- [ ] add missing pr links
- [ ] describe the change to invoke configuration elements without constructor arguments with a `{}`
- [ ] highlight seqan3::align_cfg::mode configuration 
- [ ] align_cfg::on_result has beend added
- [ ] core: std::remove_cvref_t

**Comment by marehr** [comment]
Packaging seqan3:

* [ ] use `cpack` for a source package, i.e. `seqan3-3.0.2-Source.tar.xz` (`cmake --build . --target package_source`)
* [ ] use `cpack` for a binary package, i.e. `seqan3-3.0.2-Linux.tar.xz` (`cpack`)
* [ ] sign package:
  * see https://wiki.debian.org/Creating%20signed%20GitHub%20releases
  * https://narfation.org/2013/06/23/signed-upstream-tarballs-in-debian

**Comment by marehr** [comment]
I think most of this is done, so we can close this ticket.
