### ISSUE TITLE
Argument parser wrong copyright year and missing metadata

### ISSUE THREAD

**Issue by eseiler** [seqan/seqan3#2173]
### ToDo

- [x] SeqAn copyright is 2006-2015 (fixed by #2343)
- [x] (I think one newline after the end of OPTIONS and VERSION would be enough, it's the case for all other sections) (fixed by #2287)
- [x] Print author information if available in function `seqan3::format_help_base::print_legal`(automatically prints it in all export formats)
- [x] Print EMail information if available in function `seqan3::format_help_base::print_legal`(automatically prints it in all export formats)

### Description

Code:
```cpp
#include <seqan3/argument_parser/all.hpp>

int main(int argc, char ** argv)
{
    seqan3::argument_parser parser{"App", argc, argv, seqan3::update_notifications::off};

    parser.info.author = "Foo Bar";
    parser.info.email = "foobar@example.com";
    parser.info.short_copyright = "BSD 3-Clause License";

    try
    {
        parser.parse();
    }
    catch (seqan3::argument_parser_error const & ext)
    {
        std::cerr << ext.what() << "\n";
        return -1;
    }

    return 0;
}
```

Help will print:
```
App
===

OPTIONS

  Basic options:
    -h, --help
          Prints the help page.
    -hh, --advanced-help
          Prints the help page including advanced options.
    --version
          Prints the version information.
    --copyright
          Prints the copyright/license information.
    --export-help (std::string)
          Export the help page information. Value must be one of [html, man].

  

VERSION
    Last update: 
    App version: 
    SeqAn version: 3.0.2

LEGAL
    App Copyright: BSD 3-Clause License
    SeqAn Copyright: 2006-2015 Knut Reinert, FU-Berlin; released under the 3-clause BSDL.
```

**Comment by rrahn** [comment]
### 2020-12-14

Needs some internal refactoring to DRY out code duplication.

**Comment by marehr** [comment]
@smehringer Here too, can you tell us if this can be closed? ❤️

**Comment by smehringer** [comment]
Not entirely. I updated the issue description by what is done and what is still missing :)
