### ISSUE TITLE
[Meta-Issue] Scoring Scheme Module

### ISSUE THREAD

**Issue by rrahn** [seqan/seqan3#327]
This is a meta-issue for the scoring scheme module.

# Concepts
* [x] scoring_concept

# Scoring Matrix
* [x] generic matrix used in backend. [#350]
* [x] edit 
* [x] identity: match, mismatch [how to score unknown symbols] [#351]
* [x] matrix: dna/aa
   * [ ] from file
   * [x] blossom80
   * [x] blossom62
   * [x] blossom30
   * [x] blossom45
   * [ ] pam40
   * [ ] pam120
   * [ ] pam200
   * [ ] pam250
   * [ ] vtml200

**Comment by h-2** [comment]
IIRC our original discussion came to the conclusion that we want to have two scoring scheme types, one for nucleotides and one for amino acids. All other things are run-time settings on these, or not?

**Comment by h-2** [comment]
I would propose the following interface:

  * `.get_score(dna15 const l, dna15 const r)` (or `aa27` respectively); alternatively we could use `[dna15 const l][dna15 const r]`, but that would require adding a proxy type returned by the first `operator[]`
  * `.set_matrix( )` (set custom 15x15 or 27x27 scoring matrix)
  * `.set_matrix(amino_acid_scoring_matrix )` (set BLOSUM* or PAM* via enum; only for aminoacids obviously)
  * `.set_simple_score(int match, int mismatch)` (creates the respective matrix internally)
  * `.set_file(filesystem::path p)` (do we really want this? how do we know the format? I think people should just read the values themselves and use `.set_matrix()`

I thought we also said that we want to move all gap-handling out of the scoring scheme so I think `edit` does not belong here and also there are no unknown symbols.

**Comment by rrahn** [comment]
Actually I have something in the pipeline that a) chooses the scoring scheme from the arguments and b) can hold different scoring types so that tools that use either dna or aa scoring can use the same score class without branching. But it have to see if it works. Can show you tomorrow
