### ISSUE TITLE
[meta] simd support

### ISSUE THREAD

**Issue by marehr** [seqan/seqan3#531]
The following needs to be done:

* [ ] make simd a range. I.e. provide `begin`, `end`
  * [ ] remove `debug_stream` overload
* [x] what happens when no simd can be used? scalar emulation?
* [ ] warn the user if he uses scalar fallback when explicitly using simd?

**Comment by rrahn** [comment]
@marehr I don't think that we need to follow the standard yet with proposal. We can work with our interface but should keep track of the changes in the standard and maybe add the abi_tag interface for 3.1. as a separate interface. But otherwise I am afraid we are not gonna make it for the release.
