### ISSUE TITLE
union_composition clean-up

### ISSUE THREAD

**Issue by h-2** [seqan/seqan3#60]
depends on #58 
  * [x] #68, streamline documentation, in particular: 
    * [x] add `\param` documentation to all functions
    * [x] don't use `namespace seqan3::detail::union_alphabet` since it doesn't appear in doxygen
    * [x] don't use `\privatesection` and `\publicsection` outside of class scope (it doesn't have any effect there)
    * [x] add `\ingroup composition` where needed!
  * [x] #69, streamline tests, in particular
    * [x] remove redundancy, add to generic test cases
    * [x] don't test `_value`
    * [x] tests may only depend on previously tested behaviour, there must be no circular dependencies
    * [x] don't use static_asserts, instead use TESTs
  * [x] #70, add `noexcept` where adequate

if you feel that these issues are not related, feel free to make separate PRs (i.e. not for everything, but for test VS doc for example) :smile:

**Comment by h-2** [comment]
@marehr You said you would be more motivated if the issue were split into smaller ones so feel free to start opening pull requests 😃
